# Generated by Django 4.1.2 on 2022-10-23 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_booking', models.DateTimeField(auto_now_add=True)),
                ('QR', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('numbers', models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во забронированных номеров')),
            ],
            options={
                'verbose_name': 'Забронированный отель',
                'verbose_name_plural': 'Забронированные отели',
                'ordering': ['date_booking', 'room'],
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('picture', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='картинка')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Отель')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Описание 1')),
                ('description', models.TextField(blank=True, verbose_name='Описание 2')),
                ('picture', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фотография')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('telephone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=50, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
            },
        ),
        migrations.CreateModel(
            name='RoomNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='название номера')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Название номера',
                'verbose_name_plural': 'Названия номеров',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('price', models.CharField(max_length=50)),
                ('picture', models.ImageField(default=1, upload_to='photos/%Y/%m/%d/')),
                ('img', models.ImageField(default=1, upload_to='photos/%Y/%m/%d/')),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('content', models.CharField(max_length=250)),
                ('sub_content', models.CharField(blank=True, max_length=250, verbose_name='Описание 2')),
                ('description', models.TextField(blank=True, default='Свободных номеров:', verbose_name='Описание 3')),
                ('stock', models.PositiveSmallIntegerField(default=0, verbose_name='Количество номеров')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotels.hotels')),
                ('room_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotels.roomnames')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
        migrations.CreateModel(
            name='ServicesNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='название номера')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Название услуги',
                'verbose_name_plural': 'Названия услуг',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='описание')),
                ('sub_content', models.TextField(blank=True, verbose_name='доп. описание')),
                ('picture', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='картинка')),
                ('additionally', models.TextField(verbose_name='дополнение')),
                ('tel', models.CharField(blank=True, max_length=255, verbose_name='телефон')),
            ],
            options={
                'verbose_name': 'Акции',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='StayRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stay', models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во оставшихся номеров')),
                ('booking_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotels.bookingrooms')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotels.rooms')),
            ],
            options={
                'verbose_name': 'Свободный номер',
                'verbose_name_plural': 'Свободные номера',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('price', models.CharField(max_length=50)),
                ('picture', models.ImageField(default=1, upload_to='photos/%Y/%m/%d/')),
                ('image', models.ImageField(blank=True, default=0, upload_to='photos/%Y/%m/%d/')),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('content', models.CharField(max_length=250)),
                ('sub_content', models.CharField(blank=True, max_length=250, verbose_name='Описание 2')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotels.hotels')),
                ('services_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotels.servicesnames')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.AddField(
            model_name='bookingrooms',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotels.rooms'),
        ),
    ]
